### ISSUE TITLE
Space in skin path

### ISSUE THREAD

**Issue by donker** [2sic/dnn-theme-2shine-bs5#1]
IMHO it's an antipattern to use spaces in the path names "2shine BS5".

**Comment by iJungleboy** [comment]
We'll need to discuss this internally after x-mas. If we change it, it would also affect the container names.

**Comment by ropalko** [comment]
fixed in new release ([05.00.04](https://github.com/2sic/dnn-theme-2shine-bs5/tree/05.00.04))
