### ISSUE TITLE
Login skin object does not switch to logout icon and behavior for normal users

### ISSUE THREAD

**Issue by enfJoao** [2sic/dnn-theme-2shine-bs5#10]
I'm not sure if this is a DNN issue or a theme one.
If you could test it I would greatly appreciate it.

If I login as a SU, the lock icon will switch to the open lock, and clicking it will cause a logout.
If I login as a normal user, the lock icon will remain locked, and clicking it will try to open the login ctl again and fail. The user has no way to logout.

**Comment by skarpik** [comment]
I found the same problem. On line 56 of the file theme-body.ascs, the code presently reads:

if(DotNetNuke.Security.PortalSecurity.IsInRoles(PortalSettings.AdministratorRoleName)) {

however, if this code is replaced by:

if (Request.IsAuthenticated) {

then the lock icon (logon/logoff) works properly for both administrator and regular users.

**Comment by iJungleboy** [comment]
@ropalko

**Comment by ropalko** [comment]
fixed in new release ([05.00.04](https://github.com/2sic/dnn-theme-2shine-bs5/tree/05.00.04))
