### ISSUE TITLE
Changing primary and/or secondary color

### ISSUE THREAD

**Issue by b-creative** [2sic/dnn-theme-2shine-bs5#11]
Hi,
Thanks for the great skin! 
When changing the primary and secondary colors in _variables.scss (or adding any color via a custom map-merge), these colors do NOT get a changed :root **--bs-primary-rgb** value (which should result in a changed .bg-primary class value (RGB). 

What are the best steps I should take to make these changes?

**Comment by iJungleboy** [comment]
@ropalko could you help here?

**Comment by b-creative** [comment]
And if I change the primary and secondary color values, in _variables.scss, I'm now oblegated to uncomment the merge colors part. If I don't do this, it seems that the changes are not written...

**Comment by b-creative** [comment]
ok it works! 
I added this underneath my mapmerged theme-colors part:
`$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");`


The merge part in _variables.scss now looks like this:
`$theme-colors: ();`
`$theme-colors: map-merge(`
`    (`
`        "primary":      $primary,`
`        "secondary":    $secondary,`
`        "danger":       #842029,`
`        "dark":         $gray-600`
`   ),`
`   $theme-colors`
`);`
`$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");`

Thanks

**Comment by iJungleboy** [comment]
great, congrats!
