### ISSUE TITLE
Spinners and Progress not working

### ISSUE THREAD

**Issue by boozedog** [2sic/dnn-theme-2shine-bs5#14]
Hi there,

I've tried adding spinners and progress to my page using this skin but they aren't working

```html
<div class="spinner-border" role="status">
  <span class="visually-hidden">Loading...</span>
</div>

<div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
  <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 75%"></div>
</div>
```

Other Bootstrap 5 components that I have checked seem to work fine

Any ideas?

https://getbootstrap.com/docs/5.2/components/spinners/

https://getbootstrap.com/docs/5.2/components/progress/

**Comment by iJungleboy** [comment]
Bootstrap is modular. So the SCSS can determine which styles it wants or not (to keep it lighter).

As you can see on https://github.com/2sic/dnn-theme-2shine-bs5/blob/main/src/scss/theme.scss

the spinner is currently commented out. Just activate that, and rebuild the CSS.
