### ISSUE TITLE
Bug in CSS for Language Naviation (2shine bs5 v5.3.4)

### ISSUE THREAD

**Issue by skarpik** [2sic/dnn-theme-2shine-bs5#16]
In the Language Navigation for 2shine v5.0.5, the default colors were:

- Blue (`--bs-nav-link-hover-color`) for the current language
- Black (`--bs-nav-link-color`) for the other language(s)

Additionally, none of the languages were underlined (see below):

![2shine v5 05 demo](https://github.com/user-attachments/assets/7c444246-19be-47a2-a156-aec946d05264)

In 2shine v5.3.4, both the current and other language(s) are blue and all are underlined:

![2shine v5 3 4 demo](https://github.com/user-attachments/assets/c315257d-2b53-4d33-8670-c902111fe9a9)

To remove the underlines in version 5.3.4, you can add the following line of code to `_nav-language.scss` after line 31:

Original Code:

30      a {
31        color: var(--bs-body-color);

Modified Code:

30      a {
31        color: var(--bs-body-color);
**32        text-decoration: none;**

To correct the colors of the Language Navigation, add the following code to `_base-layout.scss` after line 47:

Original Code:

40        a:not(.btn) {
41          color: var(--bs-link-color);
42
43          &:hover {
44            color: var(--bs-link-hover-color);
45          }
46        }
47

Modified Code:

40        a:not(.btn) {
41          color: var(--bs-link-color);
42
43          &:hover {
44            color: var(--bs-link-hover-color);
45          }
46        }
47
**48        #theme-page-language li a{
49          color: var(--bs-nav-link-hover-color);
50        }
51
52        #theme-page-language li:not(.active) a{
53          color: var(--bs-nav-link-color);
54        }**

These modifications work, but they might not be the most efficient or appropriate in terms of the theme's code logic.

**Comment by iJungleboy** [comment]
@ropalko could you look at this and probably pull/fix etc.?

**Comment by ropalko** [comment]
Fixed this issue and released a new version =)

**Comment by iJungleboy** [comment]
thanks @skarpik for reporting this
