### ISSUE TITLE
resx files not working after changing default language.

### ISSUE THREAD

**Issue by enfJoao** [2sic/dnn-theme-2shine-bs5#9]
Default DNN9 install with latest 2sxc and 2shine.
When I first used the theme, the imprint and privacy text and links worked.
After changing the default language to pt-PT and disabling the en-US, the text translations no longer work. I added multiple copies of my resx file (one for each possible language) to ensure at least one of them worked, but still nothing.

I added the AA and BB to make sure the links worked, and they do, so it's just the resx part not doing what it's supposed. Perhaps the function that loads the file is looking for some other pattern?

BTW, the default imprint and terms labels are reversed in the ascx.

![image](https://user-images.githubusercontent.com/26518879/172469445-eb9b7b74-077f-4ad5-91e3-1a34098b5053.png)

**Comment by eXistenZe** [comment]
Message:The following resource file caused an error while reading: C:\Inetpub\vhosts\pensaremsaude.pt\woundcare.app\portals\_default\skins\2shine bs5\app_localresources\2shine.resx

Message:The following resource file caused an error while reading: C:\Inetpub\vhosts\pensaremsaude.pt\woundcare.app\portals\_default\skins\2shine bs5\app_localresources\2shine.pt-pt.resx

**Comment by enfJoao** [comment]
Message:The following resource file caused an error while reading: ... \portals\_default\skins\2shine bs5\app_localresources\2shine.pt-pt.resx

Message:The following resource file caused an error while reading:  ... \portals\_default\skins\2shine bs5\app_localresources\2shine.resx

**Comment by enfJoao** [comment]
Nevermind. The end of the file was trimmed by whatever reason...
